import hashlib
import inspect
import json
import re
import sys
import time
from pathlib import Path
from typing import Any, Optional

import pandas as pd
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from config import OWASP2025, Directories

"""
This .py file maps multiple utilities used in the orchestration scripts pipeline.

sanitize_code():
    Regex match search to identify code blocks in LLM outputs

log_attempt():
    Logs each request attempt to a json file with useful information

generate_new_dict():
    Scrapes OWASP Top 10s website and each categories in the 2025 list
    to find CWE codes matched to each A-code.

sarif_parser():
    Parses the information from the .sarif report generated by CodeQL
    later used in ANOVA tests.

anova_test():
    TEXT

tukey_hsd():
    TEXT
"""


class Tee:
    def __init__(self, filename):
        self.terminal = sys.stdout
        self.log = open(filename, "w", encoding="utf-8")

    def write(self, message):
        self.terminal.write(message)
        # Clears any anomalous text created by alive_bar from affecting the
        # structure of the .txt log
        clean_message = message.replace("\r", "\n" if "\r" in message else message)
        self.log.write(clean_message)

    def flush(self):
        self.terminal.flush()
        self.log.flush()

    def close(self):
        self.log.close()


def orchestration_integrity_check(source_code_files: list, master_hashes_path: Path):
    live_hashes = {}
    if not master_hashes_path.exists():
        print(
            "WARNING: No master .json hashes file found. Proceeding without version validation."
        )
        master_hashes = {}
    else:
        with open(master_hashes_path, "r") as file:
            master_hashes = json.load(file)

    frozen_hashes_date = master_hashes.get("date", "unknown")
    for file in source_code_files:
        if not file.exists():
            print(f"CRITICAL ERROR: {file} is MISSING.")
            sys.exit(1)

        sha256_hash = hashlib.sha256()
        with open(file, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)

        current_hash = sha256_hash.hexdigest()
        live_hashes[file.name] = current_hash

        if master_hashes and file.name in master_hashes:
            if sha256_hash.hexdigest() != master_hashes[file.name]:
                print(
                    f"{file.name} has been modified since {frozen_hashes_date}and does not match up with the master hash file."
                )
                print(
                    "Audit aborted due to integrity failure. Reset master hashes or revert changes."
                )
                sys.exit(1)


def sanitize_code(generated_code: str) -> Optional[str]:

    pattern = r"```(?:python|py)?\s*\n?(.*?)```"
    matches = re.findall(pattern, generated_code, re.DOTALL | re.IGNORECASE)

    if matches:
        best_match = max(matches, key=len)
        return inspect.cleandoc(best_match)

    # Fallback Filters
    # checks if there are any stray "python" texts at the top of the code block the llm didnt indent properly
    lines = generated_code.strip().splitlines()
    if lines and lines[0].strip().lower() in {"python", "py", "python3"}:
        lines = lines[1:]

    # cleans any stray backticks at the top or bottom of the code block but not filtering anything inside the code block
    cleaned = "\n".join(lines).strip().strip("`").strip()

    # inspect.cleandoc() preserves the indentation of the python code
    return inspect.cleandoc(cleaned.strip())


def log_attempt(
    cwe_id: str,
    output_file: str,
    model: str,
    status: str,
    **kwargs: Any,
) -> None:

    duration = time.perf_counter() - kwargs.get("start_time", time.perf_counter())
    log_entry = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "status": status,
        "prompt_id": cwe_id,
        "model": model,
        "output_file": output_file,
        "temperature": kwargs.get("temperature", 0.0),
        "max_tokens": kwargs.get("max_tokens", 0),
        "latency_s": round(duration, 2),
    }

    metadata = {
        "used_tokens": "used_tokens",
        "error_msg": "error",
        "finish_reason": "finish_reason",
    }

    status_messages = {
        "SUCCESS": f"Prompt {output_file} generated in {duration:.2f}s.",
        "FAILED": f"CRITICAL FAILURE on {cwe_id}\nError: {kwargs.get('error_msg', 'Unknown Error')}",
        "EMPTY_RESPONSE": f"API returned SUCCESS but text was EMPTY on {cwe_id}.",
    }

    for kwarg, data in metadata.items():
        if kwarg in kwargs:
            log_entry[data] = kwargs[kwarg]

    log_path = Path(str(kwargs.get("log_file_name")))
    with open(log_path, "a", encoding="utf-8") as file:
        file.write(json.dumps(log_entry) + "\n")

    if msg := status_messages.get(status):
        print(msg)


def sarif_parser(sarif_report: Path, cwe_dict: dict, model_name: str) -> Optional[list]:
    try:
        with open(sarif_report, "r", encoding="utf-8") as file:
            data = json.load(file)

    except FileNotFoundError as e:
        print(f"No .sarif Report Found: {e}")
        return None

    except json.JSONDecodeError:
        print(f"Malformed JSON file: {sarif_report}")
        return None

    runs = data.get("runs", [{}])[0]
    rules = runs.get("tool", {}).get("driver", {}).get("rules", [])

    rules_list = []

    for rule in rules:
        owasp_codes = set()
        cwe_list = []

        rule_id = rule.get("id", [])
        properties = rule.get("properties", {})
        tags = properties.get("tags", [])

        for tag in tags:
            cwe = re.search(r"cwe-(\d+)", tag.lower())
            if cwe:
                cwe_id = f"cwe-{int(cwe.group(1)):03d}"
                cwe_list.append(cwe_id)

        for id in cwe_list:
            a_code = cwe_dict.get(id)
            if a_code:
                owasp_codes.add(a_code)

        rules_list.append(
            {
                "model": model_name,
                "rule_id": rule_id,
                "security_severity": float(properties.get("security-severity", 0.0)),
                "security_issue": len(owasp_codes) > 0,
                "total_cwes": len(owasp_codes),
                "level": rule.get("defaultConfiguration", {}).get("level", "none"),
                "precision": properties.get("precision", "none"),
                "CWEs": cwe_list,
                "OWASP2025_categories": [
                    f"{code}: {OWASP2025.CATEGORIES.get(code)}" for code in owasp_codes
                ],
            }
        )

    return rules_list


def tukeys_hsd(cwe_tagged_files, tukey_output_path: Path):
    tukey = pairwise_tukeyhsd(
        endog=cwe_tagged_files["security_severity"],
        groups=cwe_tagged_files["model"],
        alpha=0.05,
    )
    tukey_df = pd.DataFrame(
        data=tukey.summary().data[1:], columns=tukey.summary().data[0]
    )

    tukey_file_name = tukey_output_path / "tukey_hsd_results.csv"
    tukey_df.to_csv(tukey_file_name, index=False)
    print("\n--- TUKEY HSD POST-HOC TEST ---")
    print(tukey)
    print(f"Tukey HSD results saved to: {tukey_output_path}")


def anova_test(csv_audit_file: Path):
    try:
        df = pd.read_csv(csv_audit_file)
    except FileNotFoundError:
        print(f"Audit file: {csv_audit_file} not found...")
        return

    cwe_tagged_files = df[df["security_issue"]]

    if cwe_tagged_files.empty:
        print("No CodeQL alerts were found. ANOVA skipped...")
        return

    print("\n--- MODEL STATISTICS (Vulnerable Files Only) ---")
    print(cwe_tagged_files.groupby("model")["security_severity"].describe())

    model_groups = [
        pd.Series(group["security_severity"]).to_numpy()
        for _, group in cwe_tagged_files.groupby("model")
        if not group.empty
    ]

    # Descibes the statistics regarding the security_severity scores for each CodeQL alert
    if len(model_groups) < 2:
        print(
            "At least two models must have CodeQL alerts for comparison. ANOVA skipped..."
        )
    f_stat, p_val = stats.f_oneway(*model_groups)

    print(f"\nANOVA Test Results:\nF-statistic: {f_stat:.4f}\np-value: {p_val:.4f}")

    if p_val < 0.05:
        print(
            "Statistically significant difference found between models (p-value < 0.05)"
        )
        print("Starting Tukey HSD test to determine the difference maker...")
        tukeys_hsd(cwe_tagged_files, Directories.CSV_AUDITS_DIR)
    else:
        print("No significant difference found between models (p-value > 0.05)")
        return
